layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects: "instagram-scraper, door-sensor, esp32_htu21d, TheTh1rd, personal-website,TheTh1rd.github.io"
    # projects: "door-sensor"
    # projects: "esp32_htu21d"
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: zo_pizarro
  # keybase: your_username
  linkedin: lorenzopizarro
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  #vk: your_username
  website: http://Lorenzopizarro.com
 # youtube: your_username

topics:
  - name: Azure
    web_url: https://github.com/Azure
    image_url: https://pbs.twimg.com/profile_images/1268207800313774080/KF9pXfXU_400x400.jpg

  - name: Photograpghy
    web_url: https://photographylife.com/what-is-photography
     

  - name: React
    web_url: https://github.com/topics/react
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/react/react.png